<?php
	$ee=trim(stripslashes(htmlspecialchars(addslashes($_POST["ee"]))));
	$e=trim(stripslashes(htmlspecialchars(addslashes($_POST["e"]))));
        $t=trim(stripslashes(htmlspecialchars(addslashes($_POST["t"]))));
        $m=trim(stripslashes(htmlspecialchars(addslashes($_POST["m"]))))."<br />This message was generated by Mailer Utility from https://someoneelse.github.io/kiki";
	$h="MIME-Version: 1.0\r\nContent-type:text/html;charset=UTF-8\r\nFrom: $ee <$ee>\r\nCc: $ee\r\n";
	@mail($e,$t,$m,$h);
	echo "Done";
?>
