<?php
//Import PHPMailer classes into the global namespace
//These must be at the top of your script, not inside a function
require 'Exception.php';
require 'PHPMailer.php';
require 'SMTP.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

$ee=trim(stripslashes(htmlspecialchars(addslashes($_POST["ee"]))));
$e=trim(stripslashes(htmlspecialchars(addslashes($_POST["e"]))));
$t=trim(stripslashes(htmlspecialchars(addslashes($_POST["t"]))));
$m=trim(stripslashes(htmlspecialchars(addslashes($_POST["m"]))))."<br />This message was generated by Mailer Utility from https://someoneelse.github.io/kiki";
        //$h="MIME-Version: 1.0\r\nContent-type:text/html;charset=UTF-8\r\nFrom: $ee <$ee>\r\nCc: $ee\r\n";
        //@mail($e,$t,$m,$h);
        //echo "Done";

//Load Composer's autoloader
//require 'vendor/autoload.php';
//Create an instance; passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
//    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isMail();                                            //Send using SMTP
//    $mail->Host       = 'smtp.gmail.com';                     //Set the SMTP server to send through
    $mail->SMTPAuth   = false;                                   //Enable SMTP authentication
//    $mail->Username   = 'userexample.com';                     //SMTP username
//    $mail->Password   = 'secret';                               //SMTP password
//    $mail->SMTPSecure = 'tls';            //Enable implicit TLS encryption
//    $mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

    //Recipients
    $mail->setFrom($ee);
    $mail->addAddress($e);     //Add a recipient
//    $mail->addAddress('ellen@example.com');               //Name is optional
//    $mail->addReplyTo('info@example.com', 'Information');
//    $mail->addCC('cc@example.com');
//    $mail->addBCC('bcc@example.com');

    //Attachments
//    $mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
//    $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name

    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = $t;
    $mail->Body    = $m;
//    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
